version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/' # Location of requirements.txt
    schedule:
      interval: 'daily'
      timezone: 'Europe/Copenhagen'
      time: '04:00'

    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'github-actions'
    directory: '/' # Location of your GitHub workflows
    schedule:
      interval: 'daily'
      timezone: 'Europe/Copenhagen'
      time: '04:00'
